spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/yonetim
    username: root
    password: root123
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000